---
ID: "1775e4a7-6219-5793-8b29-1354b1f0d876"
Parent: "a7453f98-ebe4-5622-b8c0-72cf9c10c608"
Template: "a7453f98-ebe4-5622-b8c0-72cf9c10c608"
Path: "/sitecore/templates/Project/localdev-nextjs-demo/Styleguide-Layout-Tabs-Tab/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231205T194706Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "844f9ee7-16cb-4fca-b6cb-3d8140a9e39a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231205T194706Z
