---
ID: "6b9fc9b7-8f75-5960-bef1-232bca1bb30e"
Parent: "5d6e71f3-2c3d-58b7-81c1-7aad96ae7bc2"
Template: "5d6e71f3-2c3d-58b7-81c1-7aad96ae7bc2"
Path: "/sitecore/templates/Project/localdev-nextjs-demo/Styleguide-EditFrame/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231205T194705Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6d765c07-8498-4b9e-9f05-18fcd1328225"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231205T194705Z
